// Tiles: 0=grass, 1=tree, 2=path, 3=water
const G = 0, T = 1, P = 2, W = 3;

export const LEVELS = [
    {
        name: 'Začarovaný les',
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,P,G,G,T,T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,P,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,P,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,G,G,T,T,G,P,G,G,G,G,P,P,P,P,P,P,P,G,G,G,G,G,G,G,T],
            [T,G,G,G,P,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,T],
            [T,G,G,G,P,G,G,G,G,G,P,G,T,T,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,T],
            [T,G,G,G,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,P,P,P,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,T,T,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,P,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        enemies: [
            { x: 10, y: 5, type: 'goblin', level: 1 },
            { x: 15, y: 8, type: 'goblin', level: 1 },
            { x: 10, y: 9, type: 'goblin', level: 1 },
            { x: 21, y: 7, type: 'orc',    level: 2 },
            { x: 24, y: 12, type: 'orc',   level: 2 },
            { x: 26, y: 15, type: 'dragon', level: 3 },
        ],
        npcs: [
            { x: 3, y: 3, message: 'Vítej, hrdino! Poraž všechny příšery v lese a cesta ke hradu se otevře. Odpovídej správně na matematické příklady - za každou správnou odpověď zasadíš ránu. Pohybuj se pomocí WASD nebo šipek.' },
        ],
    },
    {
        name: 'Temné podzemí',
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,P,G,G,T,T,G,G,T,T,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,T,T,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,T,T,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,G,G,G,G,G,G,G,G,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,P,G,G,T,T,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,T,T,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,P,P,P,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        enemies: [
            { x: 10, y: 3, type: 'orc',    level: 2 },
            { x: 14, y: 6, type: 'orc',    level: 2 },
            { x: 5,  y: 8, type: 'orc',    level: 2 },
            { x: 18, y: 5, type: 'orc',    level: 2 },
            { x: 10, y: 10, type: 'dragon', level: 3 },
            { x: 20, y: 12, type: 'dragon', level: 3 },
            { x: 23, y: 15, type: 'dragon', level: 3 },
        ],
        npcs: [
            { x: 3, y: 3, message: 'Temnota se tady rychle šíří. Drak sídlí v jeskyni na východě. Musíš projít podzemím a porazit jeho stráže. Matematika je tvoje zbraň!' },
        ],
    },
    {
        name: 'Dračí doupě',
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,G,G,G,G,G,G,G,G,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,P,G,G,T,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        enemies: [
            { x: 6,  y: 3, type: 'dragon', level: 3 },
            { x: 12, y: 5, type: 'dragon', level: 3 },
            { x: 5,  y: 7, type: 'dragon', level: 3 },
            { x: 9,  y: 9, type: 'dragon', level: 3 },
            { x: 17, y: 7, type: 'dragon', level: 3 },
            { x: 17, y: 9, type: 'dragon', level: 3 },
        ],
        npcs: [
            { x: 3, y: 3, message: 'Toto je poslední oblast! Velký drak tu vládne od pradávna. Poraž všechny draky a zachráníš království! Vzpomeň na Pythagorovu větu - přijde se ti hodit.' },
        ],
    },
];
