// Tiles: 0=grass, 1=tree/wall, 2=path, 3=water
const G = 0, T = 1, P = 2, W = 3;

export const LEVELS = [
    {
        name: 'Vesnice pod Věží',
        bgColor: 0x1a2e1a,
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,T,T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T,T,G,G,G,T],
            [T,G,T,T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T,T,G,G,G,T],
            [T,G,G,G,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,P,G,T,T,G,G,G,G,G,G,T,T,G,P,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,P,G,T,T,G,G,G,G,G,G,T,T,G,P,P,P,P,P,P,P,G,G,G,G,T],
            [T,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,P,G,G,T,T,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,P,G,G,T,T,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        gate: { x: 24, y: 13 },
        enemies: [
            { x: 10, y: 5, type: 'goblin', level: 1, name: 'Zlomkový Duch' },
            { x: 14, y: 6, type: 'goblin', level: 1, name: 'Zlomkový Duch' },
            { x: 7,  y: 10, type: 'goblin', level: 1, name: 'Čtvrtinák' },
            { x: 13, y: 11, type: 'goblin', level: 1, name: 'Čtvrtinák' },
            { x: 24, y: 8,  type: 'orc',   level: 1, name: 'Půlkový Strážce' },
        ],
        npcs: [
            {
                x: 5, y: 5,
                name: 'Strážný Bohumír',
                message: '„Vítej, rytíři! Princezna Algebra je uvnitř Věže zlomků. Dej si pozor – obyčejný meč na zlomková monstra nefunguje, musíš použít hlavu! Odpovědi piš jako zlomek, např. 3/4"',
            },
        ],
    },
    {
        name: 'Zahrada Krácení',
        bgColor: 0x1a2a10,
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,T,T,P,G,G,T,T,G,G,T,T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,T,T,P,P,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,G,G,T,T,G,G,G,G,T,T,G,G,P,P,P,P,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,P,G,G,T,T,G,G,G,G,T,T,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,P,P,P,P,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,P,G,G,T,T,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,P,G,G,T,T,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        gate: { x: 22, y: 12 },
        enemies: [
            { x: 5,  y: 3, type: 'goblin', level: 2, name: 'Zkrácenec' },
            { x: 12, y: 4, type: 'goblin', level: 2, name: 'Zkrácenec' },
            { x: 7,  y: 7, type: 'orc',   level: 2, name: 'Keřový Strašák' },
            { x: 14, y: 7, type: 'orc',   level: 2, name: 'Keřový Strašák' },
            { x: 6,  y: 9, type: 'orc',   level: 2, name: 'Velký Zkrácenec' },
            { x: 20, y: 9, type: 'orc',   level: 2, name: 'Velký Zkrácenec' },
        ],
        npcs: [
            {
                x: 3, y: 3,
                name: 'Zahradník Křemínek',
                message: '„Jde ti to skvěle! Ale pamatuj – ne každé monstrum je tak velké, jak vypadá. Někdy je potřeba ho pořádně zkrátit! Odpovědi piš jako zkrácený zlomek, např. 4/8 se zkrátí na 1/2"',
            },
        ],
    },
    {
        name: 'Most přes Řeku Jmenovatelů',
        bgColor: 0x0a1a2e,
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,W,P,P,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,T],
            [T,W,P,P,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,T],
            [T,W,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,W,W,T],
            [T,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,P,W,W,T],
            [T,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,P,W,W,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        gate: { x: 26, y: 12 },
        enemies: [
            { x: 7,  y: 5, type: 'goblin', level: 3, name: 'Jmenovatelník' },
            { x: 12, y: 5, type: 'orc',    level: 3, name: 'Jmenovatelník' },
            { x: 17, y: 5, type: 'orc',    level: 3, name: 'Mostní Troll' },
            { x: 22, y: 5, type: 'dragon', level: 3, name: 'Mostní Troll' },
            { x: 26, y: 6, type: 'dragon', level: 3, name: 'Říční Démon' },
        ],
        npcs: [
            {
                x: 1, y: 1,
                name: 'Převozník Oldřich',
                message: '„Skvělá práce, hrdino! Za řekou přituhuje. Aby ses dostal dál, musíš najít společnou řeč... tedy vlastně společného jmenovatele! Např. 1/2 + 1/4: společný jmenovatel je 4, takže 2/4 + 1/4 = 3/4"',
            },
        ],
    },
    {
        name: 'Kobky Smíšených Čísel',
        bgColor: 0x0a0a0a,
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,P,G,G,T,G,G,T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,T,G,T,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,P,G,G,G,G,G,G,G,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,P,G,G,T,G,G,T,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        gate: { x: 19, y: 10 },
        enemies: [
            { x: 5,  y: 3, type: 'orc',    level: 4, name: 'Smíšenec' },
            { x: 5,  y: 6, type: 'orc',    level: 4, name: 'Smíšenec' },
            { x: 9,  y: 5, type: 'dragon', level: 4, name: 'Zlomkový Golem' },
            { x: 14, y: 6, type: 'dragon', level: 4, name: 'Zlomkový Golem' },
            { x: 10, y: 8, type: 'dragon', level: 4, name: 'Kobkový Démon' },
            { x: 18, y: 8, type: 'dragon', level: 4, name: 'Kobkový Démon' },
        ],
        npcs: [
            {
                x: 3, y: 3,
                name: 'Kostlivec Sir Zlomislav',
                message: '„Tady jsem uvízl já... Dej pozor, tyhle potvory se skládají z celého čísla a zlomku! Rozlož je a projdeš! Např. 1 a 1/2 = (1×2+1)/2 = 3/2. Odpovídej jako zlomek: 3/2"',
            },
        ],
    },
    {
        name: 'Komnata Princezny Algebry',
        bgColor: 0x1a1a2e,
        map: [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,T],
            [T,G,P,G,T,G,G,T,G,G,G,G,G,G,G,G,G,G,G,T,G,G,T,G,G,P,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,T],
            [T,G,P,G,T,G,G,T,G,G,G,G,G,G,G,G,G,G,G,T,G,G,T,G,G,P,G,G,G,T],
            [T,G,P,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,P,G,G,G,T],
            [T,G,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,G,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        playerStart: { x: 2, y: 2 },
        gate: null,
        enemies: [
            { x: 13, y: 6, type: 'boss', level: 5, name: 'Kalkulační Golem' },
        ],
        npcs: [
            {
                x: 24, y: 6,
                name: 'Princezna Algebra',
                message: '„Hah! Ty mě jdeš zachránit? Ale prosím tě! Já ty příšery stvořila, abych měla klid od hloupých nápadníků. Ale ty umíš počítat! Ukaž, jestli zvládneš můj ultimátní test – poraž mého Golem správně 3× v řadě!"',
            },
        ],
    },
];
